apiVersion: v1
kind: Namespace
metadata:
  name: web-app
  labels:
    name: web-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
  labels:
    name: ci-cd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring