apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/jenkins
