apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: ci-cd
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi